language: java
jdk:
- oraclejdk8
script: mvn clean package
addons:
  artifacts: true
deploy:
  provider: releases
  api_key:
    secure: w3+GiXxK7XBCFMh9l+J6UwdyHWRrv8R4lvApcJNBmPLOa9kFcV/FOtE/TkgL6dRHpeSrOG8ZvvV4k32RwX/Qq1e+7RptSI8T/2uudryHHLBmOykkBXnUeo6Jiv+m0cewX64DTPX0vkOR52VNNahpYmIyr28nYM46FjpCLFwIkmcyMPbjRbEM6zns+84FIO/ssL8ESO7obYrM00QCflzXpGCbY1aj8KjAHoB8IrPOnci3VQmgIAw1jq8HQXjXizWo6HXVGddGhd2HzqKENBl7o/09ti7xGkMKsB8y05LzLhvuM+WvDoKXoqRt/HngYpWzW5XynD4KaGLZ/KrNtmnKaZu5Z8vcQAkp2O990NsbemT3zMAnPj165VBI2YN5XilQlMTYfnJqbT4NwwJaib+mPzhYPypjgzzXBfHra03xmi++ivgFY9DpoVNHXzYe8CuIkvvKU7AlXyL/5kyCGDF81FuDYq42dMDKRhBPRV3ymvqs1ZyRRQC4PTvUORh9+7COxSJa/KYqykxcwMxHQiOf6fvL/8/OI+Ub2JhgrZ/PyYxApozfGwypwc/rBIxcTHkm3uhn4nW4U/hc6q3XQ/9av53qVmGOKSTvAx5xd/6tY18r5R5HPuocBApC0sGlryxDAOz9MA0JCgZ3jV6ogJJiXUNcstI3jKoaQth1a5Jhb3A=
  file: target/*.jar
  skip_cleanup: true
  file_glob: true
  on:
    repo: Exorath/ActionAPI
